import Head from 'next/head';
import { Inter } from 'next/font/google';
import cn from "clsx";
import AnimatedLink from "@/components/animated-link";
import styles from '@/styles/Home.module.scss';

const inter = Inter({ subsets: [ 'latin' ] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={cn(styles.home, inter.className)} data-page="home">
        <div className={styles.description}>
          <h1>Welcome to Ibere Next, our next js starter template</h1>
          <button>
            <AnimatedLink>Play</AnimatedLink>
          </button>
        </div>
      </section>
    </>
  );
}
